User.destroy_all
Pet.destroy_all
Job.destroy_all

User.create([
  {
    first_name: "Chanel",
    last_name: "Sparks",
    about_me: "I LOVE DOGS!!",
    address: "225 Geary St.",
    city: "San Francisco",
    state: "CA",
    zip: "94108",
    email: "csparks@unknown.com",
    password: "pizzaa",
    remote_image_url: "http://www.boostinspiration.com/wp-content/uploads/2010/09/BlackAndWhitePhotographyPeople1.jpg",
  },
  {
    first_name: "Ashley",
    last_name: "Sparks",
    about_me: "DOGS ARE THE BEST",
    address: "1230 Grant Ave",
    city: "San Francisco",
    state: "CA",
    zip: "94133",
    email: "asparks@unknown.com",
    password: "pizzaa",
    remote_image_url: "http://www.curiositytravels.org/wp-content/uploads/2015/12/IMG_6425.jpg",
  },
  {
    first_name: "Janet",
    last_name: "Sparks",
    about_me: "MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND MY DOG IS MY BEST FRIEND ",
    address: "39 New Montgomery St",
    city: "San Francisco",
    state: "CA",
    zip: "94105",
    email: "jsparks@unknown.com",
    password: "pizzaa",
    remote_image_url: "http://www.curiositytravels.org/wp-content/uploads/2015/12/IMG_6425.jpg",
  },
])




Pet.create([
  {
    name: "Fido",
    breed: "Yorkie",
    age: "10",
    user: User.first,
    remote_image_url: 'https://www.petfinder.com/wp-content/uploads/2013/05/120251710-632x3531-253x253.jpg',
    about_me: 'They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! They call me FIDO! ',
  },
  {
    name: "Mini askjdhfaksdjfh",
    breed: "Yorkie askdjfhaklsdjf",
    age: "2",
    user: User.first,
    remote_image_url: 'https://www.petfinder.com/wp-content/uploads/2012/11/253x190-e1352928841572.jpg',
    about_me: 'They call me MINI!! as;ldkfja;ds adsfkadf adfasdfasdf adf af sadf
               asdfjkal;sdf asdfa asdf asdf asdf asd arg asdf asdf asdf asdfa sadf
               alskdflakdf;laskdf asdf asdfads gasdlkfjkasd vadslfknad',
  },
  {
    name: "Pookie",
    breed: "Golden",
    age: "2",
    user: User.first,
    remote_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScvdABaCG-KYPgBh7ZrwNjWf3Q-FmgfI1WF8-WSTW_qYJ1j9kh',
    about_me: 'I am a 2 year old awesome golden!',
  },
  {
    name: "Peanut",
    breed: "Golden",
    age: "2",
    user: User.first,
    remote_image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVmAH_6jaZB1TKuxWwqDMWZ3pelBzQ-rSVuONN35HJ3x_4cqLD3Q',
    about_me: 'They call me PEANUT BC I LIKE NUTZ!',
  },
  {
    name: "Cece",
    breed: "Golden",
    age: "2",
    user: User.first,
    remote_image_url: 'http://photos.demandstudios.com/getty/article/148/149/87786680_XS.jpg',
    about_me: 'They call me CECEEEE!',
  },
  {
    name: "Johan",
    breed: "German Shepherd",
    age: 2,
    image: Rails.root.join("app/assets/images/german_shepherd.jpeg").open,
    user: User.first,
  },
  {
    name: "Sagget",
    breed: "Labrador",
    age: 1,
    image: "labrador.jpeg",
    user: User.second,
  },
  {
    name: "Jimbo",
    breed: "Rottweiler",
    age: 3,
    image: Rails.root.join("app/assets/images/rottweiler.jpeg").open,
    user: User.second,
  },
  {
    name: "Sammy",
    breed: "Beagle",
    age: 4,
    image: Rails.root.join("app/assets/images/beagle.jpeg").open,
    user: User.second,
  },
  {
    name: "Joey",
    breed: "Bulldog",
    age: 3,
    image: Rails.root.join("app/assets/images/bulldog.jpeg").open,
    user: User.second,
  },
  {
    name: "Roney",
    breed: "Golden Retriever",
    age: 2,
    image: Rails.root.join("app/assets/images/golden_retriever.jpeg").open,
    user: User.second,
  },
  {
    name: "Tim",
    breed: "Great Dane",
    age: 2,
    image: Rails.root.join("app/assets/images/great_dane.jpeg").open,
    user: User.third,
  },
  {
    name: "Tommy",
    breed: "Poodle",
    age: 5,
    image: Rails.root.join("app/assets/images/poodle.jpeg").open,
    user: User.third,
  },
  {
    name: "Dax",
    breed: "Doberman Pinscher",
    age: 2,
    image: Rails.root.join("app/assets/images/doberman_pinscher.jpeg").open,
    user: User.third,
  },
  {
    name: "Bobby",
    breed: "Dachshund",
    age: 3,
    image: Rails.root.join("app/assets/images/dachshund.jpeg").open,
    user: User.third,
  },
  {
    name: "Yar",
    breed: "Siberian Husky",
    age: 2,
    image: Rails.root.join("app/assets/images/siberian_husky.jpeg").open,
    user: User.third,
  },
])

Job.create([
  {
    title: "Need help to walk my dog for 5 days",
    description: "Walk the dog in the morning and evening",
    address: "295 Buchanan St",
    city: "San Francisco",
    state: "CA",
    zip: "94102",
    begin_date: "2017-10-07",
    end_date: "2017-10-11",
    dollar_value: 25,
    type_of_job: "Walk the dog",
    status: "Open",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-05",
    owner: User.first,
    pet: User.first.pets.sample,
  },
  {
    title: "2-day help needed for my dog",
    description: "I will be out-of-town for 2 days and need someone to look
                  after my dog during the time",
    address: "685 7th St",
    city: "San Francisco",
    state: "CA",
    zip: "94103",
    begin_date: "2017-10-09",
    end_date: "2017-10-11",
    dollar_value: 45,
    type_of_job: "Care taker",
    status: "In progress",
    recurring: "no",
    pet_location: "care taker's home",
    expiration_date: "2017-10-06",
    owner: User.first,
    pet: User.first.pets.sample,
  },
  {
    title: "Special dog needs special care",
    description: "My dog needs care for a weekend. He also needs to take
                  medications in the morning and evening.",
    address: "550 Terry A Francois Blvd",
    city: "San Francisco",
    state: "CA",
    zip: "94158",
    begin_date: "2017-10-14",
    end_date: "2017-10-15",
    dollar_value: 100,
    type_of_job: "Special care",
    status: "Completed",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-10",
    owner: User.second,
    pet: User.second.pets.sample,
  },
  {
    title: "Dog walker needed",
    description: "Walk the dog every weekday at 10:00am",
    address: "1510 Webster St",
    city: "Oakland",
    state: "CA",
    zip: "94612",
    begin_date: "2017-10-12",
    end_date: "2018-01-31",
    dollar_value: 55,
    type_of_job: "Walk the dog",
    status: "Open",
    recurring: "yes",
    pet_location: "owner's home",
    expiration_date: "2017-10-09",
    owner: User.second,
    pet: User.second.pets.sample,
    freelancer: User.third,
  },
  {
    title: "Seeking a dog pack for my dog to join in on weekend",
    description: "Any one has more than one dog? I want my puppy to have a
                  social life with a pack of dogs. Prefer a pack of minimum 3
                  dogs.",
    address: "301 Perkins St",
    city: "Oakland",
    state: "CA",
    zip: "94610",
    begin_date: "2017-10-21",
    end_date: "2017-12-16",
    dollar_value: 70,
    type_of_job: "Dog pack",
    status: "Open",
    recurring: "yes",
    pet_location: "Your place",
    expiration_date: "2017-10-05",
    owner: User.third,
    pet: User.third.pets.sample,
    freelancer: User.first,
  },
  {
    title: "Going abroad for 4 weeks and need help on my 2 puppies",
    description: "Looking for an experience caretaker for my poodles for 4 weeks
                  while I'm oversea. Willing to pay high rate. Reference
                  required.",
    address: "351 Lester Ave",
    city: "Oakland",
    state: "CA",
    zip: "94606",
    begin_date: "2017-11-01",
    end_date: "2017-11-30",
    dollar_value: 350,
    type_of_job: "Full-time care",
    status: "In progress",
    recurring: "no",
    pet_location: "Caretaker's place",
    expiration_date: "2017-10-25",
    owner: User.third,
    pet: User.third.pets.sample,
    freelancer: User.second,
  },
  {
    title: "Walk them dogs",
    description: "Walk the dog on weekdays",
    address: "2090 Clarke St",
    city: "Oakland",
    state: "CA",
    zip: "94577",
    begin_date: "2017-10-30",
    end_date: "2017-12-15",
    dollar_value: 25,
    type_of_job: "Walk the dog",
    status: "Closed",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-20",
    owner: User.first,
    pet: User.first.pets.sample,
    freelancer: User.second,
  },
  {
    title: "Take care of my dog for 1 day",
    description: "Need someone to look after my German Shepherd for a day.
                  sldkfjad asdofiasdf adf ag tadeg asdf asdfasdfaedgt asdae
                  asdfasdf adsfa sdgasd fawef aerfa sd asdfad zsdfasdfasdf
                  asdfoiaegrf asdo;ifn eaodifa asdoifhaiouf aosiudfnasduf
                  sldkfjad asdofiasdf adf ag tadeg asdf asdfasdfaedgt asdae
                  asdfasdf adsfa sdgasd fawef aerfa sd asdfad zsdfasdfasdf
                  asdfoiaegrf asdo;ifn eaodifa asdoifhaiouf aosiudfnasduf
                  sldkfjad asdofiasdf adf ag tadeg asdf asdfasdfaedgt asdae
                  asdfasdf adsfa sdgasd fawef aerfa sd asdfad zsdfasdfasdf
                  asdfoiaegrf asdo;ifn eaodifa asdoifhaiouf aosiudfnasduf",
    address: "1211 Amherst Ct",
    city: "San Leandro",
    state: "CA",
    zip: "94579",
    begin_date: "2017-10-17",
    end_date: "2017-10-17",
    dollar_value: 40,
    type_of_job: "Whole day care",
    status: "In progress",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-05",
    owner: User.first,
    pet: User.first.pets.sample,
    freelancer: User.third,
  },
  {
    title: "Gone for a weekend",
    description: "Seeking an experience individual who knows it all about dog.
                  Must be very responsible. The dog has to be fed on exact time.
                  Need a shower on both days.",
    address: "26674 Luvena Dr",
    city: "Hayward",
    state: "CA",
    zip: "94544",
    begin_date: "2017-10-07",
    end_date: "2017-10-08",
    dollar_value: 85,
    type_of_job: "Comprehensive care",
    status: "Completed",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-01",
    owner: User.second,
    pet: User.second.pets.sample,
  },
  {
    title: "Take my dog home for a day",
    description: "Looking for someone to look after my dog for a day",
    address: "39665 Fremont Blvd",
    city: "Fremont",
    state: "CA",
    zip: "94538",
    begin_date: "2017-10-19",
    end_date: "2017-10-19",
    dollar_value: 35,
    type_of_job: "One day care",
    status: "In progress",
    recurring: "no",
    pet_location: "Your place",
    expiration_date: "2017-10-07",
    owner: User.second,
    pet: User.second.pets.sample,
    freelancer: User.first,
  },
  {
    title: "Shower and fur trimming",
    description: "Looking for someone to trim the fur and shower my poodle every
                  2-weeks. Prefer Saturday, but Sunday will do",
    address: "1145 Columbine Ave",
    city: "Sunnyvale",
    state: "CA",
    zip: "94086",
    begin_date: "2017-10-21",
    end_date: "2018-10-21",
    dollar_value: 120,
    type_of_job: "Grooming",
    status: "Open",
    recurring: "no",
    pet_location: "owner's home",
    expiration_date: "2017-10-10",
    owner: User.first,
    pet: User.first.pets.sample,
    freelancer: User.third,
  },
])
